version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: postgresdb
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345679
    ports:
      - "5432:5432"

  tkns:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JWT_KEY: ${JWT_KEY}
    ports:
      - "1969:1969"
    depends_on:
      - postgres
    restart: always
