# database config
database:
  host: "postgresdb"
  port: "5432"
  user: postgres
  pass: 12345679
  name: postgres

# Lifetime in minutes
access_token_lifetime: 60m # 1 hour
refresh_token_lifetime: 43200m # 30 days

# server config
server:
  host: "0.0.0.0"
  port: "1969"
  timeout: 4s
  idle_timout: 60s